M48
; DRILL file {KiCad (7.0.0)} date Mon Feb 27 14:04:06 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-27T14:04:06+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C5.500
%
G90
G05
T1
X107.857Y-30.782
X107.857Y-151.782
X181.357Y-30.782
X181.357Y-151.782
T0
M30
